### ISSUE TITLE
Add println method to MultiProgress

### ISSUE THREAD

**Issue by mdekstrand** [console-rs/indicatif#205]
Right now, the ProgressBar has a println object, but MultiProgress does not.

I have created the [`happylog`](https://crates.io/crates/happylog) package that provides a backend to `log` for console-focused logging, and allows the program to reroute logging output to a progress bar's `println` to keep log output and progress updates from interfering with each other. In this use case, it would fit better for `MultiProgress` users to be able to reroute logging to the entire `MultiProgress`, instead of needing to pick one of the progress bars to route it to.

**Comment by marienz** [comment]
I just found indicatif and thought I needed println() on MultiProgress for much the same reason you do, and took a stab at implementing it. See https://github.com/marienz/indicatif/tree/multiprogress-println (try `cargo run --example multi-tree` to see it in action, and note the diff is much smaller with whitespace differences ignored).

There are some gotchas in using this, which is why I haven't sent a pull request yet:

1. Calling `println()` before calling `join()` doesn't print (it doesn't block, the message gets buffered and printed once `join()` is called). This is really the same caveat that already applies to progress bars, so maybe not too much of an issue: it means the MultiProgress should be registered as a logging backend immediately before calling `join()`. Note the warnings about "will deadlock your program" in the docstrings are overstating things, as far as I can tell, I'll probably tweak that wording separately.
2. Calling `join()` before adding any progress bars returns immediately. This isn't new, but it does mean any code running into `println()` not working before `join()` can't necessarily fix it by moving `join()` earlier.
3. Calling `println()` after the last progress bar finishes drops messages (they're buffered but never read). I think this is a problem for use cases like yours: I don't think there's a race-free way to unregister the MultiProgress as a logging backend after it has stopped drawing, but before it might have buffered a message. I've added a method to retrieve buffered messages that can be used to deal with this (`buffered_messages()`, also added to the multi-tree example).

I don't see a good (that is: not racy) way of making `println()` work before or after `join()`. It's fairly straightforward to make `join()` block until at least one progress bar is added, but that would be a change in behavior for code not using the new `println()` so I don't think it's a good idea. These two caveats combined do mean this new functionality is not quite as useful for happylog as you might have hoped: your users will still need to add at least one progress bar and call  `join()` close to where they reroute logging (they can't just create a MultiProgress at the start of their program and reroute logging without actually using the MultiProgress yet).

Can you try out this branch and confirm it's useful for happylog? I haven't actually used this code in practice myself yet (and it might change once I do), but I don't want to send a pull request for this if it doesn't address your use case.

**Comment by marienz** [comment]
...I take back what I said about `join()`, see #231. You might want to wait and see how that PR goes before testing this branch.

**Comment by mdekstrand** [comment]
@marienz Thanks! I don't have an opinion on #231 yet - haven't thought through the implications - but it sounds worth pursuing.

**Comment by chris-laplante** [comment]
What about something like this? I have tested it and it works. 

```
pub fn println<I: AsRef<str>>(&self, msg: I) -> ProgressBar {
    let style = ProgressStyle::default_bar().template("{msg}").on_finish(ProgressFinish::AndLeave);
    let pb = self.insert(0, ProgressBar::new(!0).with_style(style));
    pb.set_message(msg.as_ref().to_string());
    pb
}
```

**Comment by mdekstrand** [comment]
@chris-laplante thanks! Unfortunately I haven't had time to test it (lots of things on plate) but look forward to using it.
