### ISSUE TITLE
NoOp progressbar 

### ISSUE THREAD

**Issue by mpetri** [console-rs/indicatif#401]
I want to enable the user of my lib to specify if they want to see progress or not. In my code I report progress with an iterator such as:

```
items.into_par_iter().progress_with(pb).for_each(|item| ...);
```

I was wondering if it possible to create a progress bar object that I can pass into as `progress_with` that does nothing e.g:

```
let pb = if report_progress {
   let pb = ProgressBar::new(items);
   pb.set_style(..)
   pb
} else {
   ProgressBar::DoNothingBar();
};
```

if I manually increment progress I can probably achieve this with `Option<ProgressBar>` and `Some`  and `inc` but I don't know how I would do this in the case of using an iterator.

**Comment by djc** [comment]
Well, presumably you could do something like this?

```rust
if report_progress {
   items.into_par_iter().progress_with(pb).for_each(|item| ...)
} else {
   items.into_par_iter().for_each(|item| ...)
};
```

Otherwise, you could construct a `ProgressBar` with a `ProgressDrawTarget::hidden()` which would still track progress but without writing anything to the terminal. Especially with the current 0.17 rcs, the overhead of doing this should be fairly small (I've measured something like 25ns per `inc()`).

**Comment by mpetri** [comment]
thanks for the quick reply. I also found `pb.set_style(ProgressStyle::default_bar().template(""));` to not output anything but that didn't look right to me that's why I opened the issue. I agree your approach seems fine as well but if the `for_each` function is big I would need to abstract it out into a larger function to make this look clean. Closing the issue as this is probably better handled differently :)
