### ISSUE TITLE
Panic in `AtomicPosition::allow`

### ISSUE THREAD

**Issue by arxanas** [console-rs/indicatif#405]
This is the panic, from [this CI run](https://github.com/arxanas/git-branchless/runs/5596335762?check_suite_focus=true):

```
The application panicked (crashed).
Message:  attempt to add with overflow
Location: C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\indicatif-0.17.0-rc.9\src\state.rs:420
```

It corresponds to this line:

https://github.com/console-rs/indicatif/blob/ea1f7336be4320afca7dc4ad9353e64053e01343/src/state.rs#L420

Note that this is an addition which is overflowing, unlike the subtractions which are addressed in #403 and #404.

**Comment by chris-laplante** [comment]
Yep, this is the crash I've seen too. I still can't wrap my head around what is actually causing these though.

**Comment by djc** [comment]
Well, if `capacity + new` is larger than 255, that would do it? We could just do `capacity.saturating_add(new) - 1`.

**Comment by chris-laplante** [comment]
> Well, if `capacity + new` is larger than 255, that would do it? And that would happen if there's a long wait between increments.
> 
> We could just do `capacity.saturating_add(new) - 1`.

Yes. And yeah, I guess it has to be long waits that's causing it. 

Side note, but I hit this a few weeks ago and have been meaning to mention it: https://github.com/rust-lang/rust/issues/86470. It is not an indicatif bug, but rather something that was fixed in Rust. Let's maybe just keep an eye out for issue reports that may involve it.
