### ISSUE TITLE
Odd Clear Behavior in yarnish and multi example

### ISSUE THREAD

**Issue by mitsuhiko** [console-rs/indicatif#451]
This seems like a regression from what I remember. The yarnish example has 4 virtual concurrent build spinners and once they are done, three print out `waiting...` and one is cleared resulting in this:

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/?]   waiting...
[2/?]   waiting...
[3/?]   waiting...
✨  Done in 13 seconds
```

I expected either none of them to show up or all 4.

Likewise I think there is a bug in the multi example where one retains the bar:

```
starting!
pb1 is done!
[00:00:02] ########################################     128/128     done
pb3 is done!
pb2 is done!
```

Tested on 39ebd5faa898c5ab802e4ad79dcddb0224d14101. Both of those examples use the multi bar clear function.

**Comment by mitsuhiko** [comment]
I bisected it down on the yarnish example, 1d47e1dbd57bf4013e36bda3eed6a1e9f068a6b6 is the regression.

**Comment by mitsuhiko** [comment]
I think that belongs to https://github.com/console-rs/indicatif/pull/438 but I'm not entirely sure. There is no clear merge commit mentioning the PR.

**Comment by djc** [comment]
Yes, it's #438.

**Comment by chris-laplante** [comment]
I'll take a look.

**Comment by chris-laplante** [comment]
What's strange is that if you add a call to `drop(pb)` after the call to `finish_with_message` it works:

**Comment by mitsuhiko** [comment]
I cannot reproduce that it works as expected. This is fundamentally some sort of race condition so every once in a while it works when you run it. Potentially you just had a few lucky runs.

**Comment by chris-laplante** [comment]
Hah, sure enough I re-ran it and you're right :/.

**Comment by chris-laplante** [comment]
The issue here is that the zombie pruning code I added changed the semantics of `MultiProgress`. Previously, `MultiProgress` never forgot about progress bars (unless you `MultiProgress::remove`d them). That's true even if you call `finish` (or friends) on the `ProgressBar`s. Zombie pruning taught `MultiProgress` to forget about progress bars that don't exist anymore (because they got `drop`ped). Because of this, `clear` no longer clears those dropped `ProgressBar`s. 

The yarnish example is acting non-deterministically because the order in which those 4 pbs are dropped is random. Zombie pruning (and adjustment of `last_line_count`) happens in `MultiState::draw`, but `MultiState::clear` doesn't use `draw`. I haven't traced through exactly what is happening, but I don't think I'll bother because I have a proposition.

I now see that zombie pruning changes the behavior of `MultiProgress` in unintended ways. I'd like to propose turning off zombie handling by default, and making it an option you can set on `MultiProgress`. For example, `MultiProgress:set_reap_zombies(True)`. If zombie reaping is enabled, I'd also propose making `MultiProgress::clear` an illegal operation. It doesn't make sense to call `clear` on a `MultiProgress` that can't necessarily clear everything it was responsible for drawing. If a user utilizing `MultiProgress` in zombie reap mode needs to clear pbs, then they are responsible for not letting those pbs becomes zombies in the first place. 

What do you think?

**Comment by djc** [comment]
To restate the reason for introducing zombie reaping in the first place (from #426):

> Since we never call `MultiProgress::remove` on `ProgressBar`s that are dropped/finished (see #419), bars are always redrawn even when they don't need to be. When the number of bars (_n_) becomes greater than terminal lines (_m_), on each draw `MultiProgress` will clear the last _m_ lines but write _n_ lines, leaving _m - n_ lines in the scrollback history.

So could we get the terminal height from console and only reap once we run out of lines instead of requiring extra configuration/setup from the user?

**Comment by mitsuhiko** [comment]
To me it seems at least that this keeping track in `to_clear` and manually invoking `finish_and_clear` is something that the `MultiProgress` could do automatically itself?

**Comment by chris-laplante** [comment]
> So could we get the terminal height from console and only reap once we run out of lines instead of requiring extra configuration/setup from the user?

Personally I'd rather not deal with console height if we don't have to, since the user can resize the terminal whenever they want and mess us up. I think even if we did something based on height, it still wouldn't fix `clear`. Once a pb has been reaped `MultiProgress` has lost track of it. Regardless of when that happens, `clear` won't be able to touch it.

**Comment by chris-laplante** [comment]
> To me it seems at least that this keeping track in `to_clear` and manually invoking `finish_and_clear` is something that the `MultiProgress` could do automatically itself?

I think this is on the right track. `MultiProgress` should keep track of previously-reaped progress bars. The last number of lines that were printed is enough. Then `clear` just has also clear that number in addition to whatever is being displayed by the currently active set.

One wrinkle: calling `MultiProgress::println` should reset the reaped line counter to 0, since `clear` can't erase lines above the printed message without also erasing the message itself. We should do it for `MultiProgress::suspend` too - making the assumption that the user wrote something to the terminal during the suspend.

**Comment by chris-laplante** [comment]
I did some more digging on this today. I think I can fix the zombie reaping so that `MultiProgress::clear` works well, with a caveat. Previously you could do a draw operation after a `clear` (e.g. just a `tick` on some pb that's part of the `MultiProgress`) and it would be able to reconstitute everything, including stuff that had been dropped. Now that zombie reaping is a thing, that re-draw will only be able to re-draw what hasn't been reaped. 

Also, I think I can more clearly characterize the interaction between reaping and `MultiProgress::println`. `println` will be able to print lines above anything that hasn't been reaped. I don't foresee this as an issue because `MultiProgress::println` is new for 0.17.0 anyway. What do you think? Are these limitations ok?

**Comment by chris-laplante** [comment]
@djc @mitsuhiko  thoughts on above?

**Comment by mitsuhiko** [comment]
I think it makes sense.

**Comment by djc** [comment]
> I did some more digging on this today. I think I can fix the zombie reaping so that `MultiProgress::clear` works well, with a caveat. Previously you could do a draw operation after a `clear` (e.g. just a `tick` on some pb that's part of the `MultiProgress`) and it would be able to reconstitute everything, including stuff that had been dropped. Now that zombie reaping is a thing, that re-draw will only be able to re-draw what hasn't been reaped.

This seems to make sense -- remind me what the criteria for getting reaped again? Does it even make sense to tick something in a state where it can be reaped?

> Also, I think I can more clearly characterize the interaction between reaping and `MultiProgress::println`. `println` will be able to print lines above anything that hasn't been reaped. I don't foresee this as an issue because `MultiProgress::println` is new for 0.17.0 anyway. What do you think? Are these limitations ok?

Seems fine!

**Comment by chris-laplante** [comment]
> This seems to make sense -- remind me what the criteria for getting reaped again? Does it even make sense to tick something in a state where it can be reaped?

A progress bar becomes a zombie when it is `drop`ed. So you will never be able to tick it after that, no.

**Comment by chris-laplante** [comment]
Hi @mitsuhiko - when you get a chance, can you please re-test with main?

**Comment by mitsuhiko** [comment]
This seems to be resolved.
